GDSA 2015: Sessió 5.

En aquest Notebook es mostraràn els resultats obtinguts amb les funcions fetes en la sesió 4 del projecte. Aquestes funcions son: Parameters, get_local_features, train_codebook, get_assignments y build_bow. Totes aquestes sub-funcions es fan servir dins de la funció Feature_extraction.

Parameters: Aquesta funció ens permet agafar els paths dels fitxes i imatges que fem servir a les nostres funcions.

In [1]:
import os
import numpy as np
import pandas as p
#sys.path.insert(0,'E:/universidad/GDSA/proyecto/102.3')
from Parametres import parametres
from Parametres import crea_dirs
from Parametres import crea_nou_dir
param = parametres()

In [2]:
param

{'Possibles_edificis': array(['ajuntament', 'castell_cartoixa', 'catedral', 'desconegut',
        'dona_treballadora', 'escola_enginyeria', 'estacio_nord',
        'farmacia_albinyana', 'masia_freixa', 'mercat_independencia',
        'mnactec', 'societat_general', 'teatre_principal'], dtype=object),
 'arrel_entrada': 'E:/universidad/GDSA/proyecto',
 'arrel_sortida': 'E:/universidad/GDSA/proyecto/carpeta de pruebas',
 'bd_imatges': 'Terrassabuildings900/Terrassabuildings900',
 'mida_descriptor': 10}

get_local_features: Amb aquesta funció obtenim els descriptors locals de les imatges.

In [3]:
from Parametres import parametres
import cv2
from get_local_features_orb import get_local_features_orb
kp,desc = get_local_features_orb('38-29833-926.jpg')

In [4]:
len(kp),len(desc)

(20, 20)

Aquesta es la longitud de les variables que ens retorna la funció. Nombre de punts i nombre de descriptors.

train_codebook: A partir de les dades d'entrenament generem els diferents clusters que posteriorment utilitzarem per classificar les imatges

In [5]:
import cv2
from scipy.cluster.vq import  whiten,kmeans
def train_codebook(desc,k):
    whitened = whiten(desc[0:5])
    #criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 1, 1.0) 
    #a, b, c= cv2.kmeans(whitened,k,criteria,1,cv2.KMEANS_PP_CENTERS)
    #prints de comprovació, esborrar-los
    
    return kmeans(whitened, k)

In [6]:

w, distortion = train_codebook(desc,100)

In [7]:
w

array([[  0.63055687,   3.00742468,   2.08936445,   1.49073159,
          5.89787967,   3.07892578,   1.83769734,   4.18593387,
          1.34519351,   2.27688035,   0.7738554 ,   1.85572947,
          0.28094015,   1.86045962,   1.01110945,   0.84016517,
          2.30836756,   0.31995644,   1.21755519,   0.54630174,
          4.07101318,   1.15315672,   2.09383592,   0.28068323,
          2.03865087,   2.76729779,   0.05822778,  13.06509553,
          3.71113268,   1.56655416,   6.27311433,   2.95703294],
       [  2.18724413,   0.63139303,   3.41896   ,   1.60540325,
          5.4591944 ,   0.81902459,   1.24083838,   3.02043855,
          0.46727775,   5.15097522,   3.24143206,   3.57890684,
          1.38909296,   2.16688826,   2.83888422,   2.70910401,
          0.35798214,   2.80577189,   2.03505653,   2.89084673,
          4.89235795,   3.8571104 ,   3.61186696,   0.90306779,
          1.61622772,   0.57861681,   2.75999667,  14.93153775,
          3.66512691,   2.8451388 ,   3

Este valor nos muestra la distorsión entre las observaciones que le pasamos al entrenador y los centroides generados.

In [8]:
distortion

6.743495761743045e-08

get_assignments: Assigna a cada descriptor un cluster

In [9]:
from assignment import get_assignments
code, dist = get_assignments(desc, w)  

In [10]:
code

array([4, 2, 0, 1, 3, 4, 4, 2, 2, 4, 4, 4, 4, 4, 4, 4, 0, 4, 4, 4])

In [11]:
dist

array([ 11.94954019,  11.45750848,  12.03573171,  13.98764591,
        12.79143022,  14.25302294,  14.7213261 ,  14.83786887,
        13.8934981 ,  13.10942282,  14.58602915,  11.98430245,
        14.1468994 ,  16.52710356,  12.19912232,  13.23093714,
        13.49688568,  13.53252693,  14.47897831,  14.624208  ])

build_bow: Construeix un vector Back of Words normalitzat

In [12]:
import math
import numpy as np
from create_bow import build_bow
from sklearn import preprocessing
c = build_bow(code)

[ 2  1  3  1 13]


E:\universidad\GDSA\canopy\User\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
E:\universidad\GDSA\canopy\User\lib\site-packages\sklearn\utils\validation.py:420: DataConversionWarning: Data with input dtype int64 was converted to float64 by the normalize function.
  warnings.warn(msg, DataConversionWarning)


In [13]:
from codebook import train_codebook
from Parametres import parametres
from assignment import get_assignments
from get_local_features_orb import get_local_features_orb
from create_bow import build_bow
#from get_local_features_sift import get_local_features_sift
from build_database import build_database
import numpy as np
import os 
from Feature_Extraction import Feature_extraction

train_features,query_features=Feature_extraction()

[array([[ 37, 160, 241,  73, 252,  63, 225, 222, 123, 249, 244,  88, 210,
        161, 221, 188,  89, 206, 102,  24, 155, 246, 255, 210,  31,  30,
         21, 100, 195, 248, 210, 164],
       [165, 249,  57, 101,  21,  79, 103, 188, 117,  32, 102,   8, 243,
         17,  25,  48, 152, 220,  74, 106,  73, 176, 121,  63, 231, 253,
          5,  52,  64, 187,  66, 170],
       [120, 176, 153, 240, 184, 237,  81,  31, 186, 187, 173,  24, 183,
        247,  72,  26, 129, 159, 125,  24,  58, 107, 250,  19, 219, 223,
        117, 124, 224,  64, 199,  34],
       [248, 192, 102, 254,  13,  80,  92,  45, 177,  22, 231,  19, 107,
         75,  40,  83, 104, 212, 185, 226, 104,  71, 195, 207, 243, 235,
        210,  11,  51, 180, 244,  10],
       [120, 176, 153, 112, 184, 237,  81,  27, 178, 185, 181,  24, 151,
        183,  72,  24, 129, 159, 125,  24,  26, 107, 234,  17, 219, 223,
         53, 124, 192, 192, 198,  35],
       [ 33, 224, 225,  73, 205,  63, 232, 223, 127, 251, 240,  88, 138,
 

ValueError: ndim different than 1 or 2 are not supported

In [21]:
import collections
import pickle
from scipy.spatial import distance
from rank import rank
rank(query_features,train_features)

NameError: name 'query_features' is not defined